-- 코드를 입력하세요

SELECT 
    A.MONTH,
    A.CAR_ID,
    A.RECORDS
FROM
(
    SELECT
        CAST(DATE_FORMAT(START_DATE, '%y%m') AS UNSIGNED) AS S_DATE,
        CAST(DATE_FORMAT(START_DATE, '%m') AS UNSIGNED) AS MONTH,
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
    CAST(DATE_FORMAT(START_DATE, '%y%m') AS UNSIGNED) >= 2208
    AND CAST(DATE_FORMAT(START_DATE, '%y%m') AS UNSIGNED) <= 2210
    GROUP BY CAST(DATE_FORMAT(START_DATE, '%y%m') AS UNSIGNED), CAR_ID
)A
JOIN
(
    SELECT
        CAST(DATE_FORMAT(START_DATE, '%y%m') AS UNSIGNED) AS S_DATE,
        CAR_ID,
        COUNT(*) AS CNT
    FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
    CAST(DATE_FORMAT(START_DATE, '%y%m') AS UNSIGNED) >= 2208
    AND CAST(DATE_FORMAT(START_DATE, '%y%m') AS UNSIGNED) <= 2210
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)B
ON A.CAR_ID = B.CAR_ID
ORDER BY A.MONTH, A.CAR_ID DESC
;
