SELECT
     B.CATEGORY
    ,SUM(AA.SUM_SALES) AS TOTAL_SALES
FROM
(
    SELECT
         BOOK_ID
        ,SUM(SALES) AS SUM_SALES
    FROM BOOK_SALES A
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
)AA
LEFT OUTER JOIN BOOK B
ON AA.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
